# Generated by Django 2.2 on 2019-04-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OecdStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('dwellings_without_basic_facilities_as_pct', models.CharField(blank=True, db_column='Dwellings without basic facilities as pct', max_length=255, null=True)),
                ('housing_expenditure_as_pct', models.IntegerField(blank=True, db_column='Housing expenditure as pct', null=True)),
                ('rooms_per_person_as_rat', models.CharField(blank=True, db_column='Rooms per person as rat', max_length=255, null=True)),
                ('household_net_adjusted_disposable_income_in_usd', models.IntegerField(blank=True, db_column='Household net adjusted disposable income in usd', null=True)),
                ('household_net_financial_wealth_in_usd', models.IntegerField(blank=True, db_column='Household net financial wealth in usd', null=True)),
                ('labour_market_insecurity_as_pct', models.CharField(blank=True, db_column='Labour market insecurity as pct', max_length=255, null=True)),
                ('employment_rate_as_pct', models.IntegerField(blank=True, db_column='Employment rate as pct', null=True)),
                ('long_term_unemployment_rate_as_pct', models.CharField(blank=True, db_column='Long-term unemployment rate as pct', max_length=255, null=True)),
                ('personal_earnings_in_usd', models.IntegerField(blank=True, db_column='Personal earnings in usd', null=True)),
                ('quality_of_support_network_as_pct', models.IntegerField(blank=True, db_column='Quality of support network aspct', null=True)),
                ('educational_attainment_as_pct', models.IntegerField(blank=True, db_column='Educational attainment as pct', null=True)),
                ('student_skills_as_avg_score', models.IntegerField(blank=True, db_column='Student skills as avg score', null=True)),
                ('years_in_education_in_yrs', models.CharField(blank=True, db_column='Years in education in yrs', max_length=255, null=True)),
                ('air_pollution_in_ugm3', models.IntegerField(blank=True, db_column='Air pollution in ugm3', null=True)),
                ('water_quality_as_pct', models.IntegerField(blank=True, db_column='Water quality as pct', null=True)),
                ('stakeholder_engagement_for_developing_regulations_as_avg_score', models.CharField(blank=True, db_column='Stakeholder engagement for developing regulations as avg score', max_length=255, null=True)),
                ('voter_turnout_as_pct', models.IntegerField(blank=True, db_column='Voter turnout as pct', null=True)),
                ('life_expectancy_in_yrs', models.CharField(blank=True, db_column='Life expectancy in yrs', max_length=255, null=True)),
                ('self_reported_health_as_pct', models.IntegerField(blank=True, db_column='Self-reported health as pct', null=True)),
            ],
            options={
                'db_table': 'oecd_stats',
                'managed': False,
            },
        ),
    ]
